=== Azimkhan/XML/schema.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/schema" xmlns:tns="http://www.example.org/schema"
	elementFormDefault="qualified">


	<xs:element name="devices">
		
        <xs:complexType>
			<xs:sequence>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element name="cpu" type="tns:CPU"></xs:element>
				<xs:element name="ram" type="tns:RAM"></xs:element>
			</xs:choice>
			
			</xs:sequence>
			
		</xs:complexType>
    </xs:element>


	<xs:complexType name="Device">
		<xs:sequence>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element name="origin" type="xs:string" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element name="manufacturer" type="xs:string" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element name="price" type="xs:integer" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element name="critical" type="xs:boolean" minOccurs="1" maxOccurs="1">
			</xs:element>
			<xs:element name="group" type="tns:DeviceGroup" minOccurs="0" maxOccurs="1">
			</xs:element>
		</xs:sequence>

		
	</xs:complexType>

	<xs:simpleType name="DeviceGroup">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Multimedia"></xs:enumeration>
			<xs:enumeration value="Input"></xs:enumeration>
			<xs:enumeration value="Output"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>




	<xs:complexType name="CPU">
		<xs:complexContent>
			<xs:extension base="tns:Device">
					<xs:sequence>
						<xs:element name="frequency" type="tns:Frequency"/>
						<xs:element name="number_of_cores" type="xs:int"/>
						<xs:element name="number_of_threads" type="xs:int"/>
						<xs:element name="socket">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="LGA1155"></xs:enumeration>
									<xs:enumeration value="LGA2011"></xs:enumeration>
									<xs:enumeration value="AM3PLUS"></xs:enumeration>
									<xs:enumeration value="FM2"></xs:enumeration>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="cache_size" type="tns:Size"/>
					</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="RAMType">
	
		<xs:restriction base="xs:string">
			<xs:enumeration value="DDR"></xs:enumeration>
			<xs:enumeration value="DDR2"></xs:enumeration>
			<xs:enumeration value="DDR3"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:complexType name="RAM">
		<xs:complexContent>
			<xs:extension base="tns:Device">
				<xs:sequence>
					<xs:element name="frequency" type="tns:Frequency" maxOccurs="1" minOccurs="1"></xs:element>
					<xs:element name="memory_size" type="tns:Size" maxOccurs="1" minOccurs="1"></xs:element>
					<xs:element name="type" type="tns:RAMType" minOccurs="1" maxOccurs="1"></xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:simpleType name="Size">
		<xs:restriction base="xs:string">
			<xs:pattern value="[1-9][0-9]*(Mb?)?"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
						
	<xs:simpleType name="Frequency">
		<xs:restriction base="xs:string">
			<xs:pattern value="[1-9][0-9]*(\s*(Mhz|Ghz))?"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>	
</xs:schema>

=== Azimkhan/XML/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd">
	<ram>
		<name>PC10600</name>
		<origin>USA</origin>
		<manufacturer>Transcend</manufacturer>
		<price>11740</price>
		<critical>true</critical>
		<frequency>1333 Mhz</frequency>
		<memory_size>8192</memory_size>
		<type>DDR3</type>

	</ram>
	
	<cpu>
		<name>Core i3 3240</name>
		<origin>USA</origin>
		<manufacturer>Intel</manufacturer>
		<price>12350</price>
		<critical>true</critical>
		<frequency>3400Mhz</frequency>
		<number_of_cores>2</number_of_cores>
		<number_of_threads>4</number_of_threads>
		<socket>LGA1155</socket>
		<cache_size>2</cache_size>
	</cpu>

	<ram>
		<name> PC6400</name>
		<origin>Japan</origin>
		<manufacturer>Kingmax</manufacturer>
		<price>11740</price>
		<critical>true</critical>
		<frequency>1000 Mhz</frequency>
		<memory_size>2048</memory_size>
		<type>DDR2</type>
	</ram>

	<storage>
		<name>Some disk name</name>
		<origin>USA</origin>    
		<manufacturer>Transcend</manufacturer>
		<price>8430</price>
		<critical>true</critical>
		<capacity>750GB</capacity>
		<transfer_rate>1.4 Gbps</transfer_rate>
		<type>HDD</type>
		
	</storage>
	
	<peripheral>
	    <name>Officejet 7110WF</name>
	    <origin>USA</origin>
	    <manufacturer>HP</manufacturer>
	    <price>35626</price>
	    <critical>false</critical>
	    <group>Output</group>
	</peripheral>
	
</devices>
